### ISSUE TITLE
Access OpenIddict assemblies for documentation

### ISSUE THREAD

**Issue by jerriep** [openiddict/openiddict-documentation#11]
Hi @PinpointTownes ,

I want to start looking into generating the API documentation for the OpenIddict assemblies. Docfx can generate metadata for the classes in a project from the source code, and then subsequently generate the docs from that.

In the case of OpenIddict, the docs repo (this current repo) lives separately from the actual source code of the project (openiddict/openiddict-core), so for the CI server to build the docs correctly, we will somehow need to be able to reference the source code file from this repo.

Two quick options that comes to mind:
1. Add the openiddict-core repo as a git submodule to this one
2. Update the AppVeyor build script to also check out the openiddict-core repo somewhere

The first option would be most seamless probably to other people who want to contribute to this repo. The second option would mean that when people want to build the docs on their own computer, they need to manually clone the openiddict-core repo as well to the same relative path as the AppVeyor build script does, so docfx can reference those file correctly locally.

I am sure you probably have some other questions and perhaps another suggestion to handle this, so this is just to kick off the discussion

**Comment by kevinchalet** [comment]
Hey @jerriep,

Interesting. While documented, most OpenIddict APIs are not meant to be directly called by the developer ; except the managers (and the stores, for those who implement custom ones).

Do you think it would be useful to have such an API doc?

**Comment by jerriep** [comment]
It could be useful to have classes such as the `OpenIddictBuilder` documented.

I do think that in the bigger picture, there are probably better things to spend time on in terms of documentation, but this is a fairly "quick win" since the docs are already there in the XML comments. We just need to allow docfx to pick it up.

**Comment by kevinchalet** [comment]
> but this is a fairly "quick win" since the docs are already there in the XML comments. We just need to allow docfx to pick it up.

Okay. Let's opt for the submodule since it's likely the easiest option :smile:

**Comment by jerriep** [comment]
Checking out sub-modules as part of build:
https://www.appveyor.com/docs/how-to/private-git-sub-modules/#the-problem-with-private-sub-modules
