### ISSUE TITLE
Add a migration guide for moving from ASOS to OpenIddict 3.x

### ISSUE THREAD

**Issue by Darthruneis** [openiddict/openiddict-documentation#35]
### Is your feature request related to a problem?
I have been looking for information related to this process, but it seems to be rather piecemeal between the OpenIddict docs themselves (which are a good jumping off point) and searching for information in StackOverflow/github.

### Describe the solution you'd like
I would like there to be some kind of document about the basic process for migrating from ASOS to using OpenIddict. Highlighting the things that are no longer relevant, or what the new versions of the old stuff was.

### Additional context
I am trying to go through this process during the process of updating an OpenIdConnect server built on Net Framework and ASOS (a *very* early version of ASOS) to work on net5.0 and OpenIddict. 

I would be happy to contribute to such a document in any way I can as I am going through this process. 

In case it is easier to just answer some questions outright rather than creating (and maintaining) this proposed migration document, I'm going to include my current set of questions/problems:

- I am trying to figure out how to migrate a `OpenIdConnectServerProvider`-derived class that was being used on Net Framework. There's some custom code in there that hooks into the process, and I'm trying to evaluate whether that code just needs to move into a new abstraction that OpenIddict has, or if it can be removed entirely.
  - The most common code that exists in this old class is request validation - we had a custom data layer so we look up the client by the `client_id` parameter, and then verify the `client_secret`, and any `redirect_uri`s (including logout `redirect_uri`). 
    - Is this now handled automatically when using the OpenIddict data stores? The current plan was to take the existing data models we have and have them use the new OpenIddict base model(s), where applicable. 
    - How would one go about customizing this process? For example, if we have applied encryption/hashing to the `client_secret` that is being stored at rest, we would need to apply that process to the incoming `client_secret` in order to properly match.
  - A lot of the usefulness of this derived class was purely for debugging - by overriding the base class methods (and doing nothing), it made it easy to add breakpoints during local debugging. 
    - How would something like this be handled in the OpenIddict world? I realize there is the ILogger integration that may be useful in this aspect, but curious if that would be the only tool for such debugging or if the built-in extension points would facilitate this desire.  
- How to handle programmatic sign-in/sign-out. Currently this is being done at times in a service which is called from the above Provider implementation, and also during some non-OpenIddict processes such as when a user changes their password or changes some part of their information, such as their email address or name.

**Comment by Darthruneis** [comment]
Found some of the answers I was digging for, though it took more digging than I would have expected.

***
> I am trying to figure out how to migrate a `OpenIdConnectServerProvider`-derived class that was being used on Net Framework. There's some custom code in there that hooks into the process, and I'm trying to evaluate whether that code just needs to move into a new abstraction that OpenIddict has, or if it can be removed entirely.

#### Answer
The replacement for this is to implement EventHandler classes which implement `IOpenIddictServerHandler<TContext>`. There is a base class, `OpenIddictServerHandler<TContext>`, which can be used for this, but I found it intuitive enough to just implement the interface directly.

The various events in the pipeline each have corresponding context classes in the `OpenIddict.Server.OpenIddictServerEvents` static class as nested classes.

***
> The most common code that exists in this old class is request validation - we had a custom data layer so we look up the client by the `client_id` parameter, and then verify the `client_secret`, and any `redirect_uri`s (including logout `redirect_uri`).

#### Answer
This can be ported over nearly 100% by using the previously mentioned implementations of `IOpenIddictServerHandler<TContext>`.

The main thing I have found that doesn't port over, and which I believe is safe to remove, is calls to `context.Validate()`, which seems to be redundant and not needed. You either call `context.Reject` (and/or `context.SkipRequest()`), or else the context is 'valid' by default.

***
> How would one go about customizing this process? For example, if we have applied encryption/hashing to the `client_secret` that is being stored at rest, we would need to apply that process to the incoming `client_secret` in order to properly match.

#### Answer
This was able to port over pretty easily by extending the corresponding `OpenIddictEntityFramework*<>` generic classes. 

@kevinchalet A question on this point - would it be feasible for OpenIddict to use interfaces, as opposed to base classes, for this concern? The entity framework models I am working with already had a base class defined, so I had to go and rework the code that built on top of those base classes to instead use interfaces, and a consequence was that I needed to redefine some properties that were defined by those base classes/interfaces in order to use the OpenIddict base classes.

e.g., changing from this: 
```csharp
class MyApplication : OpenIddictEntityFrameworkApplication<long, MyAuthorization, MyOpenIdToken>
``` 
to 
```csharp
class MyApplication : MyBaseClass, IOpenIddictEntityFrameworkApplication<long, MyAuthorization, MyOpenIdToken>
```

***
> A lot of the usefulness of this derived class was purely for debugging - by overriding the base class methods (and doing nothing), it made it easy to add breakpoints during local debugging.
>     
>  How would something like this be handled in the OpenIddict world? I realize there is the ILogger integration that may be useful in this aspect, but curious if that would be the only tool for such debugging or if the built-in extension points would facilitate this desire.

#### Answer
My current understanding is that this would be done by implementing the `IOpenIddictServerHandler<TContext>` for the corresponding context type and using it for any debugging/logging concerns.

***
> How to handle programmatic sign-in/sign-out.

#### Answer
This one is just an ASP.NET Core difference: `HttpContext.SignInAsync/SignOutAsync`

**Comment by kevinchalet** [comment]
The demand for such a thing is extremely low, so it's hard to justify spending too much time on that. Closing.
