### ISSUE TITLE
Description about the flows

### ISSUE THREAD

**Issue by Ciantic** [openiddict/openiddict-documentation#4]
This is a placeholder,

Some description why I need all these flows, and the downsides, e.g. Password Flow is not good for anything basically cause it does not allow standard way to do two factor authentication.

Implicit is the only way for JS apps.

Code flow for other "native" apps such as iOS apps / Android apps.

**Comment by kevinchalet** [comment]
Done: https://github.com/openiddict/openiddict-documentation/commit/bc5b601d23369c44c8e61f8a2f949f0cfbd1fa6f.
